version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./infra/redis/redis.conf:/etc/redis/redis.conf:ro
      - redis_data:/data
    command: ['redis-server', '/etc/redis/redis.conf']
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis_data:
